# Generated by Django 6.1 on 2026-08-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posthistory',
            options={'ordering': ['-created_at']},
        ),
    ]
