# Generated by Django 6.1 on 2026-08-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostHistory', '0002_alter_posthistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='image_urns',
            field=models.TextField(blank=True, help_text='Comma-separated LinkedIn image URNs e.g. urn:li:image:...', null=True),
        ),
    ]
