# Generated by Django 6.1 on 2026-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostHistory', '0003_posthistory_image_urns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='context',
            field=models.TextField(),
        ),
    ]
